#!/bin/bash
# use for debugging where gosipcmd not availible

if [[ "$1" == "-z" ]]; then echo "Reset PEXOR"; exit; fi

if [[ "$1" == "-i" ]]; then echo "Initialize chain on SFP $2"; exit; fi

#writing - do nothing any output is error
if [[ "$1" == "-w" ]]; then exit; fi

if [[ "$1" == "-r" ]]; then
 
  if [[ "$2" == "--" ]]; then shift; fi
  
  echo $4;  
  exit;
fi

if [[ "$1" == "-d" ]]; then
  if [[ "$6" == "--" ]]; then
     echo Should dump data after offset scan
     exit
  fi 

  numregs=$7
  for (( cnt=0; cnt<numregs; cnt++ )) ; do
     echo "reg $cnt=$((cnt*4))"
  done
  exit;
fi

echo "wrong arguments $3" 1>&2

