// Copy tex file generated by TexDoclet.
// Replace documentclass with a4paper.
// Remove all itemlists following "Serializable",
// because they are descriptions of private members.

#include <stdio.h>
#include <string.h>
main(argc, argv)
int argc;
char *argv[];
{
  FILE *fin,*fout;
  char cin[128],cout[128],line[256],*pline;
  int out=1;
  if(argc < 3)
    {
      printf("javadco2tex inputfile outputfile\n");
      exit(0);
    }
  fin=fopen(argv[1],"r");
  if(fin == NULL)
    {
      printf("javadco2tex error: inputfile %s not found\n",argv[1]);
      exit(0);
    }
  fout=fopen(argv[2],"w");
  if(fout == NULL)
    {
      printf("javadco2tex error: inputfile %s, error opening output file %s\n",argv[1],argv[2]);
      exit(0);
    }
  pline=line;
  fgets(line,127,fin);
  strcpy(line,"\\documentclass[11pt,a4paper]{report}");
  fputs(line,fout);
  while(fgets(line,127,fin)!=NULL)
    {
      if(out) fputs(line,fout);
      if(strstr(line,"Serializable")!=NULL)out=0;
      if((out==0)&(strstr(line,"\\end{itemize}")==pline))out=1;
    }
fclose(fin);
fclose(fout);
}
