#############################################################################
# Makefile for building: First
# Generated by qmake (2.01a) (Qt 4.2.2) on: Tue Mar 13 14:34:51 2007
# Project:  First.pro
# Template: app
# Command: /home/go4/goofy/tools/qt422/bin/qmake -unix -o Makefile First.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
LEX           = flex
YACC          = yacc
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT  $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT  $(DEFINES)
LEXFLAGS      = 
YACCFLAGS     = -d
INCPATH       = -I../../../tools/qt422/mkspecs/linux-g++ -I. -I../../../tools/qt422/include/QtCore -I../../../tools/qt422/include/QtCore -I../../../tools/qt422/include/QtGui -I../../../tools/qt422/include/QtGui -I../../../tools/qt422/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/go4/goofy/tools/qt422/lib
LIBS          = $(SUBLIBS)  -L/home/go4/goofy/tools/qt422/lib -lQtGui -L/home/go4/goofy/tools/qt422/lib -L/usr/X11R6/lib -lpng -lSM -lICE -L/opt/gnome/lib -lXi -lXrender -lXrandr -lXfixes -lXcursor -lXinerama -lfreetype -lfontconfig -lXext -lX11 -lQtCore -lz -lm -lglib-2.0 -ldl -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/go4/goofy/tools/qt422/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		myUi_First.cpp \
		myui_firstapp.cpp moc_myUi_First.cpp \
		qrc_First.cpp
OBJECTS       = main.o \
		myUi_First.o \
		myui_firstapp.o \
		moc_myUi_First.o \
		qrc_First.o
DIST          = ../../../tools/qt422/mkspecs/common/unix.conf \
		../../../tools/qt422/mkspecs/common/g++.conf \
		../../../tools/qt422/mkspecs/common/linux.conf \
		../../../tools/qt422/mkspecs/qconfig.pri \
		../../../tools/qt422/mkspecs/features/qt_functions.prf \
		../../../tools/qt422/mkspecs/features/qt_config.prf \
		../../../tools/qt422/mkspecs/features/exclusive_builds.prf \
		../../../tools/qt422/mkspecs/features/default_pre.prf \
		../../../tools/qt422/mkspecs/features/release.prf \
		../../../tools/qt422/mkspecs/features/default_post.prf \
		../../../tools/qt422/mkspecs/features/warn_on.prf \
		../../../tools/qt422/mkspecs/features/qt.prf \
		../../../tools/qt422/mkspecs/features/unix/thread.prf \
		../../../tools/qt422/mkspecs/features/moc.prf \
		../../../tools/qt422/mkspecs/features/resources.prf \
		../../../tools/qt422/mkspecs/features/uic.prf \
		First.pro
QMAKE_TARGET  = First
DESTDIR       = 
TARGET        = First

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_First.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: First.pro  ../../../tools/qt422/mkspecs/linux-g++/qmake.conf ../../../tools/qt422/mkspecs/common/unix.conf \
		../../../tools/qt422/mkspecs/common/g++.conf \
		../../../tools/qt422/mkspecs/common/linux.conf \
		../../../tools/qt422/mkspecs/qconfig.pri \
		../../../tools/qt422/mkspecs/features/qt_functions.prf \
		../../../tools/qt422/mkspecs/features/qt_config.prf \
		../../../tools/qt422/mkspecs/features/exclusive_builds.prf \
		../../../tools/qt422/mkspecs/features/default_pre.prf \
		../../../tools/qt422/mkspecs/features/release.prf \
		../../../tools/qt422/mkspecs/features/default_post.prf \
		../../../tools/qt422/mkspecs/features/warn_on.prf \
		../../../tools/qt422/mkspecs/features/qt.prf \
		../../../tools/qt422/mkspecs/features/unix/thread.prf \
		../../../tools/qt422/mkspecs/features/moc.prf \
		../../../tools/qt422/mkspecs/features/resources.prf \
		../../../tools/qt422/mkspecs/features/uic.prf \
		/home/go4/goofy/tools/qt422/lib/libQtGui.prl \
		/home/go4/goofy/tools/qt422/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile First.pro
../../../tools/qt422/mkspecs/common/unix.conf:
../../../tools/qt422/mkspecs/common/g++.conf:
../../../tools/qt422/mkspecs/common/linux.conf:
../../../tools/qt422/mkspecs/qconfig.pri:
../../../tools/qt422/mkspecs/features/qt_functions.prf:
../../../tools/qt422/mkspecs/features/qt_config.prf:
../../../tools/qt422/mkspecs/features/exclusive_builds.prf:
../../../tools/qt422/mkspecs/features/default_pre.prf:
../../../tools/qt422/mkspecs/features/release.prf:
../../../tools/qt422/mkspecs/features/default_post.prf:
../../../tools/qt422/mkspecs/features/warn_on.prf:
../../../tools/qt422/mkspecs/features/qt.prf:
../../../tools/qt422/mkspecs/features/unix/thread.prf:
../../../tools/qt422/mkspecs/features/moc.prf:
../../../tools/qt422/mkspecs/features/resources.prf:
../../../tools/qt422/mkspecs/features/uic.prf:
/home/go4/goofy/tools/qt422/lib/libQtGui.prl:
/home/go4/goofy/tools/qt422/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile First.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/First1.0.0 || $(MKDIR) .tmp/First1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/First1.0.0/ && $(COPY_FILE) --parents myUi_First.h myui_firstapp.h .tmp/First1.0.0/ && $(COPY_FILE) --parents First.qrc .tmp/First1.0.0/ && $(COPY_FILE) --parents main.cpp myUi_First.cpp myui_firstapp.cpp .tmp/First1.0.0/ && $(COPY_FILE) --parents First.ui .tmp/First1.0.0/ && (cd `dirname .tmp/First1.0.0` && $(TAR) First1.0.0.tar First1.0.0 && $(COMPRESS) First1.0.0.tar) && $(MOVE) `dirname .tmp/First1.0.0`/First1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/First1.0.0


yaccclean:
lexclean:
clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


/home/go4/goofy/tools/qt422/bin/moc:
	(cd $(QTDIR)/src/tools/moc && $(MAKE))

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_myUi_First.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_myUi_First.cpp
moc_myUi_First.cpp: ui_First.h \
		myUi_First.h \
		../../../tools/qt422/bin/moc
	/home/go4/goofy/tools/qt422/bin/moc $(DEFINES) $(INCPATH) myUi_First.h -o moc_myUi_First.cpp

compiler_rcc_make_all: qrc_First.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_First.cpp
qrc_First.cpp: First.qrc \
		../../../tools/qt422/bin/rcc \
		images/fitter.png \
		images/dynlist.png \
		images/close.png \
		images/color.png \
		images/open.png
	/home/go4/goofy/tools/qt422/bin/rcc -name First First.qrc -o qrc_First.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_First.h
compiler_uic_clean:
	-$(DEL_FILE) ui_First.h
ui_First.h: First.ui
	/home/go4/goofy/tools/qt422/bin/uic First.ui -o ui_First.h

compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_image_collection_clean compiler_moc_source_clean compiler_uic_clean 

####### Compile

main.o: main.cpp ui_First.h \
		myUi_First.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

myUi_First.o: myUi_First.cpp myUi_First.h \
		ui_First.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o myUi_First.o myUi_First.cpp

myui_firstapp.o: myui_firstapp.cpp myui_firstapp.h \
		myUi_First.h \
		ui_First.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o myui_firstapp.o myui_firstapp.cpp

moc_myUi_First.o: moc_myUi_First.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_myUi_First.o moc_myUi_First.cpp

qrc_First.o: qrc_First.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_First.o qrc_First.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

