// Copy tex file generated by TexDoclet.
// Replace documentclass with a4paper.
// Remove all itemlists following "Serializable",
// because they are descriptions of private members.
 
#include <stdio.h>
#include <string.h>
main(argc, argv)
int argc;
char *argv[];
{
  int out;
  char line[256];
  while(fgets(line,256,stdin)!=NULL)
    {
    out=1;
    if(strlen(line)>1){
      if(strstr(line,"hyperref")!=NULL)out=0;
      if(strstr(line,"texmf")!=NULL)out=0;
      if(strstr(line,"erfull")!=NULL)out=0;
      if(strstr(line,"[][]")!=NULL)out=0;
      if(out)fputs(line,stdout);
    }}
    exit(0);
}
