// Copy output generated by pdflatex.
// skips Underfull, Overfull, hyperref, empty lines etc. 
#include <stdio.h>
#include <string.h>
main(argc, argv)
int argc;
char *argv[];
{ int out;
  char line[256];
  while(fgets(line,256,stdin)!=NULL)
    {
    out=1;
    if(strlen(line)>1){
      if(strstr(line,"hyperref")!=NULL)out=0;
      else if(strstr(line,"texmf")!=NULL)out=0;
      else if(strstr(line,"erfull")!=NULL)out=0;
      else if(strstr(line,"[][]")!=NULL)out=0;
      if(out)fputs(line,stdout);
  }}
  exit(0);
}
