## Include dependencies rules

ifndef Dabc_Makefile_rules
Dabc_Makefile_rules = true

AUTO_DIRS = $(sort $(CREATE_DIRS) $(dir $(ALLDEPENDENC))) 

build-init::

ifdef DABCMAINMAKE
AUTO_DIRS += $(sort $(dir $(ALLHDRS))) 
build-init:: $(ALLHDRS)
endif

ifneq ($(APPLICATIONS_DIRS),)
apps::
	@for DIR in $(APPLICATIONS_DIRS); do ($(MAKE) -f $$DIR/Makefile DABCSYS=$(DABCSYS) _topdir_=$$DIR/) done
endif


clean::
	@echo "Clean in $(CURDIR)" 
	@for DIR in $(APPLICATIONS_DIRS); do ($(MAKE) clean -f $$DIR/Makefile DABCSYS=$(DABCSYS) _topdir_=$$DIR/) done
	@for DIR in $(AUTO_DIRS); do (if [ ! -f $$DIR ] ; then rm -rf $$DIR; fi); done
	@rm -rf $(BLD_DIR) 

clean-svn:
	find . -name ".svn" -type d -exec rm -rf {} \;
	@echo "Clean svn-specific files done"


ifeq ($(DOOPTIMIZATION), false)
OPTFLAGS = $(DEBUGMODE)
else
OPTFLAGS = $(OPTIMIZEMODE)
endif

$(BLD_DIR)/dummy.d: $(AUTO_DIRS) build-init 
	@(if [ ! -f $(BLD_DIR) ] ; then mkdir -p $(BLD_DIR); fi)
	@(if [ ! -f $@ ] ; then touch $@; fi)

$(AUTO_DIRS):
	@for DIR in $@; do (if [ ! -f $$DIR ] ; then mkdir -p $$DIR; fi); done

## Extensions rules

.SUFFIXES: .$(SrcSuf) .$(DepSuf) .$(HedSuf) .$(CSuf)

$(BLD_DIR)/%.$(ObjSuf): %.$(SrcSuf)
	$(CXX) -c $< $(OPTFLAGS) $(CXXFLAGS) -o $@ 

%.$(ObjSuf): %.$(SrcSuf)
	$(CXX) -c $< $(OPTFLAGS) $(CXXFLAGS) -o $@ 

$(BLD_DIR)/%.$(ObjSuf): %.$(CSuf)
	$(CC) -c $< $(OPTFLAGS) $(CFLAGS) -o $@

$(BLD_DIR)/%.$(DepSuf): %.$(SrcSuf)
	@echo "Dependency: $@"
	@$(MakeDepend) "$(CXXFLAGS)" $@  $<  $*

%.$(DepSuf): %.$(SrcSuf)
	@echo "Dependency: $@"
	@$(MakeDepend) "$(CXXFLAGS)" $@  $<  $*

$(BLD_DIR)/%.$(DepSuf): %.$(CSuf)
	@echo "Dependency: $@"
	@$(MakeDepend) "$(CFLAGS)" $@  $<  $* 

## include in the end, if necessary, dependency and dummy.h file 
 
ifeq ($(findstring $(MAKECMDGOALS), $(FASTRULES)),)

ifdef ALLDEPENDENC
# before dependency can be created one need all headers
$(ALLDEPENDENC) : $(ALLHDRS)
-include $(ALLDEPENDENC)
endif

## this must be last include in complete makefile
-include $(BLD_DIR)/dummy.d

endif
	
endif
	