## Include dependencies rules

ifndef Dabc_Makefile_rules
Dabc_Makefile_rules = true

BLD_DIRS += $(sort $(dir $(ALLHDRS))) 
BLD_DIRS += $(sort $(dir $(ALLDEPENDENC))) 

build-init:: $(ALLHDRS)

clean::
	@echo "Clean in $(CURDIR) dirs: $(BLD_DIRS)" 
	@for DIR in $(BLD_DIRS); do (if [ ! -f $$DIR ] ; then rm -rf $$DIR; fi); done
	@rm -rf $(BLD_DIR) 

ifeq ($(DOOPTIMIZATION), false)
OPTFLAGS = $(DEBUGMODE)
else
OPTFLAGS = $(OPTIMIZEMODE)
endif

$(BLD_DIR)/dummy.d: $(BLD_DIRS) build-init 
	@(if [ ! -f $(BLD_DIR) ] ; then mkdir -p $(BLD_DIR); fi)
	@(if [ ! -f $@ ] ; then touch $@; fi)

$(BLD_DIRS):
	@echo "Build all dirs $(BLD_DIR)"
	@for DIR in $@; do (if [ ! -f $$DIR ] ; then mkdir -p $$DIR; fi); done

## Extentions rules

.SUFFIXES: .$(SrcSuf) .$(DepSuf) .$(HedSuf) .$(CSuf)

$(BLD_DIR)/%.$(ObjSuf): %.$(SrcSuf)
	$(CXX) -c $< $(OPTFLAGS) $(CXXFLAGS) -o $@ 

$(BLD_DIR)/%.$(ObjSuf): %.$(CSuf)
	$(CC) -c $< $(OPTFLAGS) $(CFLAGS) -o $@

$(BLD_DIR)/%.$(DepSuf): %.$(SrcSuf)
	@echo "Dependency: $@"
	@$(MakeDepend) "$(CXXFLAGS)" $@  $<  $*

$(BLD_DIR)/%.$(DepSuf): %.$(CSuf)
	@echo "Dependency: $@"
	@$(MakeDepend) "$(CFLAGS)" $@  $<  $* 

## include in the end, if necessary, dependency and dummy.h file 
 
ifeq ($(findstring $(MAKECMDGOALS), $(FASTRULES)),)

ifdef ALLDEPENDENC
-include $(ALLDEPENDENC)
endif

## this must be last include in complete makefile
-include $(BLD_DIR)/dummy.d

endif
	
endif
	