#! /bin/bash
# dabclogin
# first version 01-Jul-2008, Joern Adamczewski gsi
# added optional argument to be able to set a local DABCSYS, 18-Jul-2008, HE
# modified for refactorized workspace 06-11-2008 JAM
# removed xdaq, added some aliases    17-02-2009 JAM
#
echo
echo "***********************************************************************"
echo "*** dabclogin setting up Data Acquisition Backbone Core environments..."
if [ -z "$GSI_OS_FLAVOR" ] 
    then . /usr/local/bin/gsi_environment.sh
fi

VERSIONPATH=/usr/local/pub/$GSI_OS_FLAVOR$GSI_OS_VERSION/$GSI_COMPILER_CC
# look for explicit DABCSYS
if [ $# -eq 0 ]
then
export DABCSYS=$VERSIONPATH/dabc/dabc/dabc
else
export DABCSYS=$1
fi
#------------------------------------
# cleanup old library path:
  IFSOLD=$IFS
  NEWPATH=
  IFS=':'
  for dir in $LD_LIBRARY_PATH
    do
#    echo testing $dir from ldpath
    para=`echo $dir |awk '{gsub(".*dabc.*","");print $0}'`   
    if [ -n "$para" ]; then
#	echo keeping $para in ldpath
	NEWPATH=$NEWPATH':'$para
    fi  
  done
  IFS=$IFSOLD
  export LD_LIBRARY_PATH=${NEWPATH#:}
# cleanup old path:
  IFSOLD=$IFS
  NEWPATH=
  IFS=':'
  for dir in $PATH
    do
#    echo testing $dir from path
    para=`echo $dir |awk '{gsub(".*dabc.*","");print $0}'`    
    if  [ -n "$para" ]; then
#	echo keeping $para in path
	NEWPATH=$NEWPATH':'$para
    fi  
  done
  IFS=$IFSOLD
  export PATH=${NEWPATH#:}
# cleanup old classpath:
   IFSOLD=$IFS
  NEWPATH=
  IFS=':'
  for dir in $CLASSPATH
    do
#    echo testing $dir from classpath
    para=`echo $dir |awk '{gsub(".*dabc.*","");print $0}'`   
    if [ -n "$para" ]; then
#	echo keeping $para in classpath
	NEWPATH=$NEWPATH':'$para
    fi 
  done
  IFS=$IFSOLD
  export CLASSPATH=${NEWPATH#:}

#--------------------------------
# the dim part:
export DIMDIR=$VERSIONPATH/dabc/dim/dim
ODIR=linux
OS=Linux

export DIMDIR ODIR OS
export LD_LIBRARY_PATH=$DIMDIR/$ODIR:$LD_LIBRARY_PATH



alias dimTestServer=$DIMDIR/$ODIR/testServer
alias dimTestClient=$DIMDIR/$ODIR/testClient
alias dimTest_server=$DIMDIR/$ODIR/test_server
alias dimTest_client=$DIMDIR/$ODIR/test_client
alias dimDns=$DIMDIR/$ODIR/dns
alias dim_get_service=$DIMDIR/$ODIR/dim_get_service
alias dim_send_command=$DIMDIR/$ODIR/dim_send_command
alias dimBridge=$DIMDIR/$ODIR/DimBridge
alias dimDid=$DIMDIR/$ODIR/did
echo "*** enabled DIM at $DIMDIR ."


#----------------------------------
# the dabc part:

# was set above
#export DABCSYS=$VERSIONPATH/dabc/dabc/dabc

export PATH=$DABCSYS/bin:$PATH


export LD_LIBRARY_PATH=.:$DABCSYS/lib:$LD_LIBRARY_PATH

#-----------------------------------
# java gui part:
#export CLASSPATH=.:$DABCSYS/gui/java/generic/:$DIMDIR/jdim/classes
export CLASSPATH=.:$DABCSYS/gui/java/packages/xgui.jar:$DIMDIR/jdim/classes
alias dabc="java -Xmx200m xgui.xGui -dabc"
alias dabs="java -Xmx200m xgui.xGui -dabs"
alias moni="java -Xmx200m xgui.xGui -moni"
alias mbs="java -Xmx200m xgui.xGui -mbs"
alias guru="java -Xmx200m xgui.xGui -guru"

# Qt configurator frontend:
#. /usr/local/bin/qtlogin 303-04
#alias dabcConfigurator="$DABCSYS/gui/Qt/mbs-configurator/Configurator"

echo "*** set DABC system directory to $DABCSYS ."
echo "***********************************************************************"
echo "*** Please set the DIM_DNS_NODE environment for the gui!" 
echo "*** Type dabc to start pure DABC gui"
echo "*** Type mbs  to start pure MBS gui"
echo "*** Type dabs to start combined DABC/MBS gui"
echo "*** Ready." 
