/* Generated by Together */

#include "DABCWorker.h"
#include "DABCRegistry.h"
#include "DABCManager.h"


XDAQ_INSTANTIATOR_IMPL(dabc::xd::Worker)


dabc::xd::Worker::Worker(xdaq::ApplicationStub* stub)
	throw (xdaq::exception::Exception)
	: dabc::xd::Node(stub)
{	
   Manager()->SetMainManager(false); 
}	


dabc::xd::Worker::~Worker()
{
   
}

XDAQ_INSTANTIATOR_IMPL(dabc::xd::Eventbuilder)
XDAQ_INSTANTIATOR_IMPL(dabc::xd::Readout)



