// $Id$

/************************************************************
 * The Data Acquisition Backbone Core (DABC)                *
 ************************************************************
 * Copyright (C) 2009 -                                     *
 * GSI Helmholtzzentrum fuer Schwerionenforschung GmbH      *
 * Planckstr. 1, 64291 Darmstadt, Germany                   *
 * Contact:  http://dabc.gsi.de                             *
 ************************************************************
 * This software can be used under the GPL license          *
 * agreements as stated in LICENSE.txt file                 *
 * which is part of the distribution.                       *
 ************************************************************/

#ifndef HTTP_Civetweb
#define HTTP_Civetweb

#ifndef HTTP_Server
#include "http/Server.h"
#endif

#include "civetweb.h"

namespace http {

   /** \brief %Server provides http access to DABC
    *
    */

   class Civetweb : public Server  {
      protected:
         int fHttpPort;              ///< port number for HTTP server
         int fHttpsPort;             ///< port number for HTTPS server
         std::string fAuthFile;      ///< authentification file, generated by htdigest utility
         std::string fAuthDomain;    ///< realm parameter in authentification, dabc@server is default
         std::string fSslCertif;     ///< SSL certificate file name in plm format

         struct mg_context *   fCtx;
         struct mg_callbacks   fCallbacks;

         virtual void OnThreadAssigned();

      public:
         Civetweb(const std::string& name, dabc::Command cmd = 0);
         virtual ~Civetweb();

         virtual const char* ClassName() const { return "HttpServer"; }

         static int begin_request_handler(struct mg_connection *conn);
   };
}

#endif
