/* Generated by Together */

#ifndef DABC_XD_EXCEPTION_H
#define DABC_XD_EXCEPTION_H
#include <xcept/Exception.h>
namespace dabc{
namespace xd{
//namespace exception{
    
/**
 * General exception class to be used in Fdaq framework. 
 */
class Exception : public xcept::Exception {
    
public:    
    
   Exception( std::string name, std::string message, std::string module, int line, std::string function ):
                                        xcept::Exception(name, message, module, line, function){}
   Exception( std::string name, std::string message, std::string module, int line, std::string function, xcept::Exception & e ):
                                        xcept::Exception(name, message, module, line, function, e) {}

};
//}
}
}
#endif //EXCEPTION_H
