/* Generated by Together */

#ifndef DABC_XD_WORKER_H
#define DABC_XD_WORKER_H
#include "DABCNode.h"


namespace dabc{
namespace xd{

/**
 * This is the application node that actual is working dataflow
 */
class Worker : public dabc::xd::Node {
public:
    XDAQ_INSTANTIATOR();

    Worker(xdaq::ApplicationStub* as) throw (xdaq::exception::Exception);

    
	virtual ~Worker();

      
};


class Eventbuilder : public dabc::xd::Worker {
public:
    XDAQ_INSTANTIATOR();

    Eventbuilder(xdaq::ApplicationStub* as) throw (xdaq::exception::Exception)
    : dabc::xd::Worker(as)
    {;}

    
	virtual ~Eventbuilder(){;}
};

class Readout : public dabc::xd::Worker {
public:
    XDAQ_INSTANTIATOR();

    Readout(xdaq::ApplicationStub* as) throw (xdaq::exception::Exception)
    : dabc::xd::Worker(as)
    {;}

    
	virtual ~Readout(){;}
};


} // end namespace xd
} // end namespace dabc


#endif //DABCWORKER_H
