/* Generated by Together */

#ifndef DABC_XD_CONTROLLER_H
#define DABC_XD_CONTROLLER_H
#include "DABCNode.h"
//#include <xdata/UnsignedInteger.h> 


#define _DABC_SERVICE_SYSTEMDIR_   "Setup_SystemPath"
#define _DABC_SERVICE_USERDIR_     "Setup_UserPath"
#define _DABC_SERVICE_USER_        "Setup_User"
#define _DABC_SERVICE_SETUP_       "Setup_File"
#define _DABC_SERVICE_SETUPINFO_   "Setup_Info"




namespace dabc{
namespace xd{ 

class Controller : public dabc::xd::Node {
public:
    XDAQ_INSTANTIATOR();

    Controller(xdaq::ApplicationStub* as) throw (xdaq::exception::Exception);;

    
	virtual ~Controller();

    virtual void actionPerformed (xdata::Event& e); 

protected: 
   
    /** Name of the cluster setup file (set by controller gui)*/
    xdata::String setupFile_;

     /** Name of the user that started cluster (set by controller gui)*/
    xdata::String setupUser_; 

  /** DABCSYS on startup of cluster (set by controller gui)*/
    xdata::String setupSystemDir_; 
    
    /** Working directory on startup of cluster (set by controller gui)*/
    xdata::String setupUserDir_;   
    
    
};
} // end namespace xd
} // end namespace dabc
#endif //DABC_XD_CONTROLLER_H
